### ISSUE TITLE
Unable to run songs from playlist

### ISSUE THREAD

**Issue by shivamkalra** [spcmd/spotymenu#1]
Thanks for the wonderful tool. I tried it today but I'm unable to get playlist to work. I've created two playlists and copied their URIs to `~/.spotymenu/playlists` file (pipe delimited). On typing `:p` command I do get names of playlist but nothing happens on selecting them (no console messages either).

Any ideas? I'll go through code myself to figure it out but if you know the problem let me know.

**Comment by spcmd** [comment]
Is your playlists file looks something like this?

Playlist1Name|spotify:user:_YourSpotifyUsername_:playlist:_NumbersAndLetters_
Playlist2Name|spotify:user:_YourSpotifyUsername_:playlist:_NumbersAndLetters_

_NumbersAndLetters_ of course course are the spotify ids of the playlists.

You need to right click on the playlist in Spotfiy and select the **Copy Spotify URI**  (Not the _Copy Playlist Link_).

**Comment by shivamkalra** [comment]
It looks like this only. It is not public, does it make difference?

**Comment by spcmd** [comment]
If you are logged in to the Spotify client it should work with private playlists. None of my playlists are public, and I don't have this problem.

You can try to check manually whether you get the proper URI with this command:

`awk -F '|' 'index($0, "YourPlaylistName"){print $NF}' ~/.spotymenu/playlists | head -n 1`

Just set your playlist's name between the quotes (and of course modify the path if it's not `~/.spotymenu/playlists` for your. By default it is).

If the command gives back a proper URI (`spotify:user:YourSpotifyUsername:playlist:NumbersAndLetters`) then it should work.

I assume you have a working dbus on your system.

**Comment by shivamkalra** [comment]
Same problem persists. I ran your command and it looks OK.

I ran the command:
`
awk -F '|' 'index($0, "YourPlaylistName"){print $NF}' ~/.spotymenu/playlists | head -n 1`

I get following:
`
spotify:user:userName:playlist:5ZMixAgbq....GBUHnNu`

My spotify client version is: 1.0.26.125.g64dc8bc6

**Comment by spcmd** [comment]
Strange. I'm using exactly this version under Arch Linux.

Does it work if you run the dbus command directly from the terminal?

```
dbus-send --print-reply=literal --session --type=method_call --dest=org.mpris.MediaPlayer2.spotify /org/mpris/MediaPlayer2 org.mpris.MediaPlayer2.Player.OpenUri "string:spotify:user:userName:playlist:5ZMixAgbq....GBUHnNu"
```

It should open the playlist in Spotify. But It won't start playing it unfortunately.

**Comment by shivamkalra** [comment]
spcmd notifications@github.com writes:

> Strange. I'm using exactly this version under Arch Linux.
> 
> Does it work if you run the dbus command directly from the terminal?
> 
> `dbus-send --print-reply=literal --session --type=method_call --dest=org.mpris.MediaPlayer2.spotify /org/mpris/MediaPlayer2 org.mpris.MediaPlayer2.Player.OpenUri "string:spotify:user:userName:playlist:5ZMixAgbq....GBUHnNu"`
> 
> It should open the playlist in Spotify. But It won't start playing it unfortunately.
> 
> ---
> 
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/spcmd/spotymenu/issues/1#issuecomment-205675596

I get  `dbus-send: Unknown type "spotify"`. But I do use dbus-send for
play/pause/next/previous buttons on my system.

## 

  -- Shivam

**Comment by spcmd** [comment]
Then it's some problem with the dbus. Maybe try that command by removing the `--session` from it. If it doesn't work either, maybe try that command but change the `--session` to `--system`:

```
dbus-send --print-reply=literal --system --type=method_call --dest=org.mpris.MediaPlayer2.spotify /org/mpris/MediaPlayer2 org.mpris.MediaPlayer2.Player.OpenUri "string:spotify:user:userName:playlist:5ZMixAgbq....GBUHnNu"
```

**Comment by shivamkalra** [comment]
@spcmd I just realize that playlist won't play automatically. Sorry about that. The functionality works as expected. We can close this issue. However it would be amazing to somehow get playlist play automatically.
